package iptv

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.util.Base64

/**
 * Embeds byte-exact fixture files as base64 constants in generated Kotlin test sources, so every Kotlin target
 * (JVM and Kotlin/Native) reads the same bytes without file I/O. Constants are chunked below the JVM class-file
 * constant limit.
 */
abstract class EmbedFixtureBytes : DefaultTask() {
    /** Kotlin property name → fixture file. */
    @get:Internal
    abstract val fixtures: MapProperty<String, java.io.File>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    val fixtureFiles: Collection<java.io.File>
        get() = fixtures.get().values

    @get:Input
    val fixtureNames: Collection<String>
        get() = fixtures.get().keys

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val objectName: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        val out = StringBuilder()
        out.appendLine("// GENERATED by EmbedFixtureBytes from tooling/fixtures. Do not edit.")
        out.appendLine("package $pkg")
        out.appendLine()
        out.appendLine("import kotlin.io.encoding.Base64")
        out.appendLine()
        out.appendLine("internal object ${objectName.get()} {")
        for ((name, file) in fixtures.get().toSortedMap()) {
            val encoded = Base64.getEncoder().encodeToString(file.readBytes())
            val chunks = encoded.chunked(CHUNK)
            out.appendLine("    /** ${file.name} (${file.length()} bytes) */")
            out.appendLine("    val $name: ByteArray get() = Base64.decode(")
            out.appendLine("        listOf(")
            chunks.forEach { out.appendLine("            \"$it\",") }
            out.appendLine("        ).joinToString(\"\"),")
            out.appendLine("    )")
        }
        out.appendLine("}")
        val target = outputDir.get().file(pkg.replace('.', '/') + "/${objectName.get()}.kt").asFile
        target.parentFile.mkdirs()
        target.writeText(out.toString())
    }

    private companion object {
        const val CHUNK = 30_000
    }
}
