package app.iptvplayer.protocols.m3u

import app.iptvplayer.domain.error.ValidationFailure
import app.iptvplayer.domain.id.PlaylistId
import app.iptvplayer.domain.net.ParsedUrl
import app.iptvplayer.domain.ports.ByteSource
import app.iptvplayer.domain.ports.CollectingDiagnosticSink
import app.iptvplayer.domain.ports.ImportDiagnostic
import app.iptvplayer.domain.ports.ParseLimits
import app.iptvplayer.domain.ports.ParseOutcome
import app.iptvplayer.domain.security.PercentEncoding
import app.iptvplayer.domain.security.Secret
import app.iptvplayer.domain.security.SensitiveUrl
import app.iptvplayer.protocols.content.ContentItem
import app.iptvplayer.protocols.content.ImportCounts
import app.iptvplayer.protocols.content.SourceCredentials
import app.iptvplayer.protocols.io.PrefixReplaySource
import app.iptvplayer.protocols.io.readPrefix
import app.iptvplayer.protocols.sniff.ContentSniffer
import app.iptvplayer.protocols.sniff.SniffedFormat

public class M3uImportResult(
    public val outcome: ParseOutcome,
    public val sniffedFormat: SniffedFormat,
    public val counts: ImportCounts,
    public val diagnostics: List<ImportDiagnostic>,
    public val diagnosticCounts: Map<String, Int>,
)

/**
 * VALIDATE → PARSE → NORMALIZE → MATCH/DEDUPLICATE for one M3U body (docs/IPTV_PROTOCOLS.md §6). FETCH, PERSIST,
 * INDEX and PUBLISH belong to the ingestion pipeline and are not part of this class. Items are emitted incrementally;
 * nothing is buffered beyond per-import identity state.
 */
public object M3uImporter {
    public fun import(
        source: ByteSource,
        playlistId: PlaylistId,
        credentials: SourceCredentials? = null,
        limits: ParseLimits = ParseLimits.M3U,
        emit: (ContentItem) -> Unit,
    ): M3uImportResult {
        val diagnostics = CollectingDiagnosticSink(limits.maxDiagnostics)
        val prefix = readPrefix(source, ContentSniffer.SNIFF_BYTES)
        val sniffed = ContentSniffer.sniff(prefix)
        val rejection = when (sniffed) {
            SniffedFormat.M3U, SniffedFormat.UNKNOWN -> null
            SniffedFormat.HLS_PLAYLIST -> ValidationFailure.SOURCE_IS_HLS_PLAYLIST
            SniffedFormat.HTML -> ValidationFailure.UNEXPECTED_CONTENT_TYPE_HTML
            SniffedFormat.EMPTY -> ValidationFailure.EMPTY_RESPONSE
            SniffedFormat.XMLTV, SniffedFormat.XML_OTHER, SniffedFormat.JSON, SniffedFormat.GZIP -> ValidationFailure.UNRECOGNIZED_FORMAT
        }
        if (rejection != null) {
            return M3uImportResult(ParseOutcome.Rejected(rejection), sniffed, ImportCounts(), emptyList(), emptyMap())
        }

        val normalizer = M3uNormalizer(playlistId, credentials, emit, diagnostics)
        val outcome = M3uParser().parse(PrefixReplaySource(prefix, source), limits, { record ->
            when (record) {
                is M3uRecord.Header -> normalizer.onHeader(record)
                is M3uRecord.Entry -> normalizer.onEntry(record)
            }
        }, diagnostics)

        val finalOutcome = if (outcome == ParseOutcome.Completed && sniffed == SniffedFormat.UNKNOWN && normalizer.acceptedItems == 0) {
            ParseOutcome.Rejected(ValidationFailure.UNRECOGNIZED_FORMAT)
        } else {
            outcome
        }
        return M3uImportResult(finalOutcome, sniffed, normalizer.counts, diagnostics.diagnostics, diagnostics.countsByCode)
    }
}

/** An M3U URL generated by an Xtream Codes panel; the user can be offered API mode instead (§3.4). */
public class XtreamM3uCandidate(
    public val baseUrl: String,
    public val username: Secret<String>,
    public val password: Secret<String>,
    public val outputFormat: String?,
) {
    override fun toString(): String = "XtreamM3uCandidate(baseUrl=$baseUrl, outputFormat=$outputFormat)"
}

public object XtreamM3uDetector {
    public fun detect(url: SensitiveUrl): XtreamM3uCandidate? {
        val parsed = ParsedUrl.parse(url.unsafeRawValue()) ?: return null
        if (!parsed.hasAuthority || !parsed.path.endsWith("/get.php")) return null
        val params = parsed.query?.split('&')?.mapNotNull { pair -> queryParameter(pair) }?.toMap() ?: return null
        val username = params["username"]?.ifEmpty { null } ?: return null
        val password = params["password"]?.ifEmpty { null } ?: return null
        val base = "${parsed.scheme}://${parsed.hostAndPort}${parsed.path.removeSuffix("/get.php")}"
        return XtreamM3uCandidate(base, Secret(username), Secret(password), params["output"])
    }

    private fun queryParameter(pair: String): Pair<String, String>? {
        val eq = pair.indexOf('=')
        if (eq <= 0) return null
        val name = PercentEncoding.decode(pair.substring(0, eq), plusAsSpace = true).lowercase()
        return name to PercentEncoding.decode(pair.substring(eq + 1), plusAsSpace = true)
    }
}
