import groovy.json.JsonSlurper

plugins {
    id("iptv.kmp-library")
}

val generateFixtureVectors = tasks.register<GenerateFixtureVectors>("generateFixtureVectors") {
    val fixtures = layout.projectDirectory.dir("../../tooling/fixtures")
    stateMachine.set(fixtures.file("playback/state-machine.json"))
    idVectors.set(fixtures.file("ids/id-vectors.json"))
    outputDir.set(layout.buildDirectory.dir("generated/fixtureVectors/commonTest/kotlin"))
}

kotlin {
    sourceSets {
        commonTest {
            kotlin.srcDir(generateFixtureVectors)
        }
    }
}

/**
 * Turns the language-neutral fixtures in tooling/fixtures into Kotlin test data, so every Kotlin target
 * (JVM and Kotlin/Native) runs the same vectors without file I/O or a JSON dependency.
 */
abstract class GenerateFixtureVectors : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val stateMachine: RegularFileProperty

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val idVectors: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val sm = JsonSlurper().parse(stateMachine.get().asFile) as Map<*, *>
        val ids = JsonSlurper().parse(idVectors.get().asFile) as Map<*, *>
        val out = StringBuilder()
        out.appendLine("// GENERATED by :shared:domain:generateFixtureVectors from tooling/fixtures. Do not edit.")
        out.appendLine("package app.iptvplayer.domain.fixtures")
        out.appendLine()
        out.appendLine("internal data class StateVector(val name: String, val mode: String, val steps: List<Pair<String, String>>)")
        out.appendLine("internal data class TextVector(val input: String, val normKey: String, val matchNormalize: String)")
        out.appendLine(
            "internal data class IdVector(val kind: String, val prefix: String, val kindName: String, val scope: String, val parts: List<String>, val id: String)",
        )
        out.appendLine("internal data class ShaVector(val input: String, val hex: String)")
        out.appendLine("internal data class FingerprintVector(val input: String, val fingerprint: String)")
        out.appendLine()
        out.appendLine("internal object StateMachineFixture {")
        out.appendLine("    val initial: String = ${lit(sm["initial"] as String)}")
        out.appendLine("    val modes: List<String> = listOf(${(sm["modes"] as List<*>).joinToString { lit(it as String) }})")
        out.appendLine("    val states: List<String> = listOf(${(sm["states"] as List<*>).joinToString { lit(it as String) }})")
        out.appendLine("    val events: List<String> = listOf(${(sm["events"] as List<*>).joinToString { lit(it as String) }})")
        out.appendLine("    /** Key: \"STATE|event|mode\"; value: target state or \"ignore\". */")
        out.appendLine("    val transitions: Map<String, String> = mapOf(")
        val modes = (sm["modes"] as List<*>).map { it as String }
        (sm["transitions"] as Map<*, *>).forEach { (state, row) ->
            (row as Map<*, *>).forEach { (event, target) ->
                modes.forEach { mode ->
                    val resolved = if (target is Map<*, *>) target[mode] as String else target as String
                    out.appendLine("        ${lit("$state|$event|$mode")} to ${lit(resolved)},")
                }
            }
        }
        out.appendLine("    )")
        out.appendLine("    val vectors: List<StateVector> = listOf(")
        (sm["vectors"] as List<*>).forEach { v ->
            val vector = v as Map<*, *>
            val steps = (vector["steps"] as List<*>).joinToString { step ->
                val pair = step as List<*>
                "${lit(pair[0] as String)} to ${lit(pair[1] as String)}"
            }
            out.appendLine("        StateVector(${lit(vector["name"] as String)}, ${lit(vector["mode"] as String)}, listOf($steps)),")
        }
        out.appendLine("    )")
        out.appendLine("}")
        out.appendLine()
        out.appendLine("internal object IdFixture {")
        out.appendLine("    val versionTag: String = ${lit(ids["versionTag"] as String)}")
        out.appendLine("    val text: List<TextVector> = listOf(")
        (ids["text"] as List<*>).forEach { t ->
            val m = t as Map<*, *>
            out.appendLine(
                "        TextVector(${lit(m["input"] as String)}, ${lit(m["normKey"] as String)}, ${lit(m["matchNormalize"] as String)}),",
            )
        }
        out.appendLine("    )")
        out.appendLine("    val ids: List<IdVector> = listOf(")
        (ids["ids"] as List<*>).forEach { i ->
            val m = i as Map<*, *>
            val parts = (m["parts"] as List<*>).joinToString { lit(it as String) }
            out.appendLine(
                "        IdVector(${lit(
                    m["kind"] as String,
                )}, ${lit(
                    m["prefix"] as String,
                )}, ${lit(m["kindName"] as String)}, ${lit(m["scope"] as String)}, listOf($parts), ${lit(m["id"] as String)}),",
            )
        }
        out.appendLine("    )")
        out.appendLine("    val fingerprints: List<FingerprintVector> = listOf(")
        (ids["fingerprints"] as List<*>).forEach { f ->
            val m = f as Map<*, *>
            out.appendLine("        FingerprintVector(${lit(m["input"] as String)}, ${lit(m["fingerprint"] as String)}),")
        }
        out.appendLine("    )")
        out.appendLine("    val sha256: List<ShaVector> = listOf(")
        (ids["sha256"] as List<*>).forEach { s ->
            val m = s as Map<*, *>
            out.appendLine("        ShaVector(${lit(m["input"] as String)}, ${lit(m["hex"] as String)}),")
        }
        out.appendLine("    )")
        out.appendLine("}")

        val file = outputDir.get().file("app/iptvplayer/domain/fixtures/FixtureVectors.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(out.toString())
    }

    /** Kotlin string literal with every non-printable-ASCII UTF-16 unit escaped. */
    private fun lit(value: String): String = buildString {
        append('"')
        for (c in value) {
            when {
                c == '\\' -> append("\\\\")
                c == '"' -> append("\\\"")
                c == '$' -> append("\\$")
                c.code in 0x20..0x7E -> append(c)
                else -> append("\\u").append(c.code.toString(16).padStart(4, '0'))
            }
        }
        append('"')
    }
}
